version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - deepseek
  - embd
  - evagpt
  - jaxtyping
  - memmap
  - openwebtext
  - resid
  - silu
  - Skylion
  - swiglu
  - tril
ignoreWords: []
import: []
